tabs:
    fields:
        ####################################################
        # Theme
        ####################################################
        theme_section:
            tab: Šablona
            label: Šablona
            type: section
        theme_site_name:
            tab: Šablona
            label: Název webu
            type: text
        ####################################################
        # General
        ####################################################
        company_section:
            tab: Obecné
            label: Název společnosti
            type: section
        company_first_name:
            tab: Obecné
            label: První část názvu
            type: text
            span: left
        company_last_name:
            tab: Obecné
            label: Druhá část názvu
            type: text
            span: right
        company_logo_section:
            tab: Obecné
            label: Logo společnosti
            type: section
        company_logo:
            tab: Obecné
            label: Logo společnosti
            type: fileupload
            mode: image
        ####################################################
        # Contact
        ####################################################
        contact_section:
            tab: Kontakt
            label: Kontakt
            type: section
        contact_email:
            tab: Kontakt
            label: Kontaktní e-mail
            type: email
        contact_phone:
            tab: Kontakt
            label: Kontaktní telefon
            type: text
        contact_name:
            tab: Kontakt
            label: Jméno a příjmení
            type: text
        contact_address:
            tab: Kontakt
            label: Adresa
            type: text